// AUTO-GENERATED by scripts/core_gen_ts.py from twobme_common.types + contracts/*.yaml.
// Do not edit by hand. Regenerate: uv run python scripts/core_gen_ts.py
/* eslint-disable */

export type Modality = "keyboard" | "mouse" | "scroll" | "workflow" | "temporal";
export type Mode = "enroll" | "monitor";
export type Label = "genuine" | "impostor";
export type Actor = "a" | "b" | "guest";
export type Pointer = "trackpad" | "mouse";
export type Level = "learning" | "normal" | "watch" | "suspicious" | "locked";
export type Binding = "co-present" | "remote";
export type Channel = "desktop" | "web";
export type Role = "user" | "admin";
export type MarkerLabel = "takeover_start" | "takeover_end" | "note" | "rearm" | "reset";
export type OsEventKind = "screen_locked" | "screen_unlocked" | "sleep" | "wake";
export type ChallengeTrigger = "proactive" | "step_up" | "unlock" | "redteam" | "sandbox";
export type ChallengeStatus = "issued" | "prompt_ended" | "scoring" | "retry" | "fallback_mfa" | "verified" | "blocked_spoof" | "blocked_impostor" | "expired" | "cancelled";
export type VoiceDecision = "VERIFY" | "RETRY" | "FALLBACK_MFA" | "BLOCK_SPOOF" | "BLOCK_IMPOSTOR";
export type DecisionAction = "view" | "export" | "add_payee" | "password_change" | "purchase";
export type DecisionKind = "allow" | "step_up" | "block";
export type TransStatus = "Y" | "C" | "N";
export type Tier = "R0" | "R1" | "R2" | "R3";
export type AnomalyKind = "trust_drop" | "takeover_suspected" | "voice_spoof" | "voice_impostor" | "lock" | "redteam_tool";
export type ModelStatus = "none" | "training" | "ready" | "failed";
export type LiveType = "snapshot" | "trust" | "block_scored" | "context" | "enroll_progress" | "model" | "anomaly" | "challenge" | "voice_stage" | "voice_result" | "decision" | "marker" | "mode" | "lock" | "unlock" | "label" | "presence" | "health" | "feed";

export interface Display {
  w_pt: number;
  h_pt: number;
  hz: number;
}

export interface Block {
  modality: Modality;
  t_start: string;
  t_end: string;
  n: number;
  features: Record<string, number | null>;
  transitions: Record<string, number> | null;
  psd: number[] | null;
}

export interface Deviation {
  feature: string;
  z: number;
}

export interface BlockScore {
  modality: Modality;
  t_end: string;
  n: number;
  typicality: number | null;
  llr_direct: number | null;
  top: Deviation[];
}

export interface ModalityContribution {
  typicality: number | null;
  llr: number;
  q: number;
  w: number;
  delta: number;
  n_blocks: number;
}

export interface TrustState {
  t: number;
  logit: number;
  delta_logit: number;
  confidence: number;
  display: number;
  level: Level;
  per_modality: Partial<Record<Modality, ModalityContribution>>;
  reasons: string[];
}

export interface Hello {
  type: "hello";
  v: number;
  device_token: string;
  run_id: string;
  resume_session_id: string | null;
  requested_mode: Mode | null;
  agent_version: string;
  schema_version: number;
  os: string;
  pointer: Pointer;
  display: Display;
  last_unlock_at: string | null;
}

export interface TickFlags {
  secure_input: boolean;
  injected: number;
  pointer: Pointer;
  late: boolean;
  idle_s: number;
  clock_skew: boolean;
}

export interface TickCounts {
  keys: number;
  mouse_moves: number;
  clicks: number;
  scroll_events: number;
  app_switches: number;
}

export interface Tick {
  type: "tick";
  run_id: string;
  session_id: string | null;
  seq: number;
  t_end: string;
  flags: TickFlags;
  counts: TickCounts;
  activity: number[];
  blocks: Block[];
  context: Block | null;
}

export interface MarkerMsg {
  type: "marker";
  label: "takeover_start" | "takeover_end" | "note";
  t: string;
  text: string | null;
}

export interface OsEventMsg {
  type: "os_event";
  event: OsEventKind;
  t: string;
}

export interface DemoMsg {
  type: "demo";
  action: "reset";
}

export interface ClockPing {
  type: "clock_ping";
  t0_ns: number;
}

/** POST /api/agent/ticks — HTTPS fallback while the WS is down (Bearer device token). */
export interface AgentTicksIn {
  ticks: Tick[];
}

export interface AgentTicksOut {
  accepted: number;
  duplicates: number;
}

export interface Welcome {
  type: "welcome";
  device_id: string;
  user_id: string;
  session_id: string;
  mode: Mode;
  model_version: number | null;
  label: Label;
  actor: Actor;
}

export interface AgentModalityTrust {
  llr: number;
  delta: number;
}

export interface AgentTrust {
  type: "trust";
  seq: number | null;
  confidence: number;
  display: number;
  level: Level;
  locked: boolean;
  per_modality: Partial<Record<Modality, AgentModalityTrust>>;
}

export interface AgentChallenge {
  type: "challenge";
  challenge_id: string;
  trigger: ChallengeTrigger;
  verify_url: string;
  expires_at: string | null;
  open_browser: boolean;
}

export interface AgentLock {
  type: "lock";
  reason: string;
}

export interface AgentUnlock {
  type: "unlock";
}

export interface AgentMode {
  type: "mode";
  mode: Mode;
}

export interface ClockPong {
  type: "clock_pong";
  t0_ns: number;
  server_ns: number;
}

export interface AgentError {
  type: "error";
  code: string;
  detail: string | null;
}

export interface Spectrogram {
  f_hz: number[];
  t_s: number[];
  db: number[][];
}

export interface VoiceResult {
  decision: VoiceDecision;
  voice_confidence: number;
  asv_cos: number | null;
  cm_p_spoof: number | null;
  spec_sim: number | null;
  phrase_wer: number | null;
  onset_ms: number | null;
  dsp: Record<string, number>;
  findings: string[];
  stage_ms: Record<string, number>;
  spectrogram: Spectrogram | null;
}

export interface ChallengeOut {
  challenge_id: string;
  trigger: ChallengeTrigger;
  status: ChallengeStatus;
  attempt: number;
  phrase: string;
  prompt_url: string;
  expires_at: string | null;
  verify_url: string;
}

export interface ResolvedDecision {
  decision_id: string;
  decision: DecisionKind;
  trans_status: TransStatus;
}

export interface VoiceOutcome {
  device_locked: boolean;
  resolved_decisions: ResolvedDecision[];
}

/** hearsay.score_audio(...) result (profile 'stepup' | 'hearsay'). */
export interface CMResult {
  margin: number;
  p_spoof: number | null;
  llr: number | null;
  analyzers: Record<string, number>;
  ms: Record<string, number>;
}

export interface VoiceEnrollStartOut {
  enroll_id: string;
  phrases: string[];
}

export interface VoiceEnrollOut {
  enrolled: boolean;
  n_utts: number;
  intra_cos: number | null;
}

export interface ChallengeCreateIn {
  reason: "unlock" | "redteam" | "sandbox";
}

export interface NextPhrase {
  phrase: string;
  prompt_url: string;
  expires_at: string | null;
  attempt: number;
}

export interface ChallengeResponseOut {
  result: VoiceResult;
  outcome: VoiceOutcome;
  next: NextPhrase | null;
}

export interface TotpVerifyIn {
  challenge_id: string;
  code: string;
}

export interface TotpVerifyOut {
  ok: boolean;
  outcome: VoiceOutcome;
}

export interface TotpEnrollOut {
  otpauth_uri: string;
}

export interface RedteamActiveOut {
  challenge_id: string;
  phrase: string;
  status: ChallengeStatus;
}

export interface LoginIn {
  email: string;
  password: string;
}

export interface DeviceOut {
  id: string;
  label: string;
  pointer: Pointer | null;
  mode: Mode;
  locked: boolean;
  lock_reason: string | null;
  last_seen: string | null;
}

export interface MeOut {
  user_id: string;
  email: string;
  handle: string;
  role: Role;
  totp_enrolled: boolean;
  device: DeviceOut | null;
}

export interface DeviceRegisterIn {
  label?: string;
  os?: string | null;
  pointer?: Pointer | null;
  display?: Display | null;
}

export interface DeviceRegisterOut {
  device_id: string;
  device_token: string;
}

export interface PresenceBucket {
  t_s: number;
  keys: number;
  pointer: number;
  wheel: number;
}

export interface PresenceIn {
  buckets: PresenceBucket[];
  client_now_ms?: number | null;
}

export interface PresenceOut {
  binding: Binding;
  score: number | null;
  device_id: string | null;
}

export interface EnrollModeIn {
  device_id: string;
  mode: Mode;
}

export interface EnrollTrainIn {
  device_id: string;
  source?: "tiger" | "logs";
}

export interface RetrainIn {
  device_id: string;
}

export interface JobOut {
  job_id: string;
}

export interface EnrollProgress {
  mode: Mode;
  counts: Partial<Record<Modality, number>>;
  gates: Partial<Record<Modality, number>>;
  ready: boolean;
}

export interface ModelInfo {
  status: ModelStatus;
  job_id: string | null;
  version: number | null;
  trained_at: string | null;
  n_blocks: Partial<Record<Modality, number>>;
  enabled_modalities: Modality[];
  metrics: Record<string, unknown>;
  headline_medians: Record<string, number | null>;
  learned_since_enroll: number;
  parent_version: number | null;
  error: string | null;
}

export interface DecisionIn {
  action: DecisionAction;
  amount_cents?: number | null;
}

export interface CheckoutIn {
  amount_cents: number;
  card_last4: string;
}

export interface DecisionOut {
  decision_id: string;
  status: "final" | "pending";
  decision: DecisionKind;
  trans_status: TransStatus;
  confidence: number;
  tier: Tier;
  binding: Binding;
  reasons: string[];
  challenge_id: string | null;
  verify_url: string | null;
}

export interface DecisionDetailOut extends DecisionOut {
  action: DecisionAction;
  amount_cents: number | null;
  final_decision: DecisionKind | null;
  final_trans_status: TransStatus | null;
  resolved_at: string | null;
}

export interface DemoLabelIn {
  device_id: string;
  label: Label;
  actor: Actor;
}

export interface DemoMarkerIn {
  device_id: string;
  label: MarkerLabel;
  text?: string | null;
}

export interface DemoDeviceIn {
  device_id: string;
}

export interface DemoRearmIn {
  device_id: string;
  confidence?: number;
}

export interface PurgeSessionIn {
  session_id: string;
}

export interface OkOut {
  ok: boolean;
  detail: string | null;
}

export interface TrustPoint {
  t: string;
  confidence: number;
  level: Level;
}

export interface MarkerPoint {
  t: string;
  label: MarkerLabel;
  text: string | null;
}

export interface DeviationOut {
  feature: string;
  label: string;
  unit: string;
  z: number;
}

export interface LiveDevice {
  id: string;
  label: string;
  pointer: Pointer | null;
  mode: Mode;
  locked: boolean;
  lock_reason: string | null;
  last_seen: string | null;
}

export interface TrustLive extends TrustState {
  seq: number | null;
  locked: boolean;
}

export interface BlockScored {
  modality: Modality;
  t_start: string;
  t_end: string;
  n: number;
  typicality: number | null;
  llr: number | null;
  q: number | null;
  delta: number | null;
  top: DeviationOut[];
}

export interface ContextLive {
  psd: number[] | null;
  features: Record<string, number | null>;
  enrolled_psd: number[] | null;
}

export interface AnomalyLive {
  id: string;
  kind: AnomalyKind;
  severity: number;
  trust_before: number | null;
  trust_after: number | null;
  top_features: DeviationOut[];
  action: string | null;
  challenge_id: string | null;
  explanation: string | null;
}

export interface ChallengeLive {
  challenge_id: string;
  trigger: ChallengeTrigger;
  status: ChallengeStatus;
  attempt: number;
  expires_at: string | null;
  verify_url: string | null;
}

/** VoiceResult without the spectrogram, plus challenge_id. */
export interface VoiceResultLive {
  challenge_id: string;
  decision: VoiceDecision;
  voice_confidence: number;
  asv_cos: number | null;
  cm_p_spoof: number | null;
  spec_sim: number | null;
  phrase_wer: number | null;
  onset_ms: number | null;
  dsp: Record<string, number>;
  findings: string[];
  stage_ms: Record<string, number>;
}

/** Streaming step-up stage (transcribing -> anti-spoof -> speaker -> spectral). */
export interface VoiceStageLive {
  challenge_id: string;
  stage: "transcribing" | "anti-spoof" | "speaker" | "spectral" | "done";
  ok: boolean | null;
  value: number | null;
}

export interface DecisionLive extends DecisionOut {
  action: DecisionAction;
  amount_cents: number | null;
}

export interface ModeLive {
  mode: Mode;
}

export interface LockLive {
  reason: string;
}

export interface LabelLive {
  label: Label;
  actor: Actor;
}

export interface PresenceLive {
  binding: Binding;
  score: number | null;
}

/** Dashboard health pills. */
export interface HealthLive {
  heartbeat_age_s: number | null;
  tap_events_per_s: number | null;
  secure_input: boolean;
  last_block_age_s: Partial<Record<Modality, number | null>>;
  rtt_ms: number | null;
  voice_warm: boolean;
  elevenlabs_quota: number | null;
  activity: number[];
}

export interface FeedItem {
  t: string;
  type: string;
  text: string;
  severity: number;
}

export interface Snapshot {
  device: LiveDevice | null;
  session_id: string | null;
  label: Label;
  actor: Actor;
  trust: TrustLive | null;
  trust_history: TrustPoint[];
  markers: MarkerPoint[];
  model: ModelInfo | null;
  enroll: EnrollProgress | null;
  open_challenge: ChallengeLive | null;
  recent_events: FeedItem[];
  last_tick_json: Record<string, unknown> | null;
  health: HealthLive | null;
  enrolled_psd: number[] | null;
}

export interface LiveEnvelope {
  type: LiveType;
  device_id: string | null;
  t: string;
  data: Record<string, unknown>;
}

export interface SessionRow {
  session_id: string;
  device_id: string | null;
  user_id: string;
  channel: Channel;
  status: string;
  started_at: string;
  ended_at: string | null;
  n_ticks: number;
  avg_confidence: number | null;
  min_confidence: number | null;
  n_anomalies: number;
  n_markers: number;
}

export interface TrustBucket {
  t: string;
  avg: number | null;
  min: number | null;
  max: number | null;
  last: number | null;
  n_stepups: number;
}

export interface TrustSeries {
  session_id: string | null;
  bucket: string;
  points: TrustBucket[];
  markers: MarkerPoint[];
}

export interface AnomalyRow {
  id: string;
  time: string;
  kind: AnomalyKind;
  severity: number;
  device_id: string | null;
  session_id: string | null;
  trust_before: number | null;
  trust_after: number | null;
  top_features: DeviationOut[];
  action: string | null;
  challenge_id: string | null;
  challenge_decision: string | null;
  explanation: string | null;
  resolution: string | null;
}

export interface BaselineRow {
  feature: string;
  column: string;
  label: string;
  unit: string;
  session_median: number | null;
  baseline_mean: number | null;
  baseline_std: number | null;
  z: number | null;
}

export interface BaselineOut {
  modality: Modality;
  session_id: string | null;
  rows: BaselineRow[];
}

export interface HypertableStat {
  name: string;
  total_chunks: number;
  compressed_chunks: number;
  before_bytes: number | null;
  after_bytes: number | null;
  ratio: number | null;
  rows_estimate: number | null;
}

export interface TigerJob {
  job_id: number;
  proc: string;
  hypertable: string | null;
  schedule_interval: string | null;
  last_run_status: string | null;
  next_start: string | null;
}

export interface TigerStats {
  ok: boolean;
  hypertables: HypertableStat[];
  jobs: TigerJob[];
  caggs: string[];
  extensions: Record<string, string>;
  cached_at: string | null;
}

export interface DriftRow {
  t: string;
  column: string;
  z: number | null;
}

export interface WriterStats {
  queued: number;
  dropped: number;
  flushed: number;
  failed_batches: number;
  last_flush_at: string | null;
}

export interface StatusOut {
  ok: boolean;
  version: string;
  uptime_s: number;
  tiger: "up" | "down";
  voice_warm: boolean;
  demo_mode: boolean;
  continuous_update: boolean;
  writer: WriterStats;
  devices_online: number;
  elevenlabs: Record<string, unknown> | null;
  inference: Record<string, unknown> | null;
}

export interface EvalModality {
  auc: number | null;
  eer: number | null;
  roc: [number, number][];
  n_genuine: number;
  n_impostor: number;
  beta: number | null;
  weak: boolean;
}

export interface EvalFused {
  auc: number | null;
  eer: number | null;
}

export interface EvalAblation {
  removed: Modality;
  fused_eer: number | null;
}

export interface EvalIdentification {
  labels: string[];
  confusion: number[][];
  accuracy: number | null;
}

export interface EvalLiveTrial {
  t_start: string;
  ttd_s: number | null;
  detected: boolean;
}

export interface EvalSpliceTtd {
  median: number | null;
  p90: number | null;
  values: number[];
}

export interface EvalSplice {
  n: number;
  ttd_s: EvalSpliceTtd;
  undetected_300s_frac: number | null;
  fa_per_hour: Record<string, number>;
  r3_friction_frac: number | null;
}

export interface EvalReport {
  generated_at: string;
  n_blocks: Record<string, Record<string, number>>;
  modalities: Partial<Record<Modality, EvalModality>>;
  fused: EvalFused;
  ablation: EvalAblation[];
  identification: EvalIdentification | null;
  live_trials: EvalLiveTrial[];
  splice: EvalSplice | null;
  notes: string[];
}

export interface RedteamCount {
  n: number;
  frr: number | null;
  far: number | null;
}

export interface RedteamAttack {
  class: string;
  generator: string;
  n: number;
  far_asv_only: number | null;
  far_cm_only: number | null;
  far_fused: number | null;
  mean_asv_cos: number | null;
}

export interface RedteamReport {
  generated_at: string;
  delivery: "acoustic" | "injected";
  thresholds: Record<string, number>;
  genuine: RedteamCount;
  impostor: RedteamCount;
  attacks: RedteamAttack[];
}

export interface HearsayDev {
  n: number;
  min_dcf_a: number | null;
  min_dcf_b: number | null;
  eer: number | null;
}

export interface HearsayDetector {
  name: string;
  min_dcf_a: number | null;
  min_dcf_b: number | null;
}

export interface HearsayReport {
  generated_at: string;
  rules_confirmed: boolean;
  dev: HearsayDev;
  detectors: HearsayDetector[];
  fusion: Record<string, unknown> | string | null;
  ablation: Record<string, unknown>[];
}

export type AgentMessage =
  | Hello
  | Tick
  | MarkerMsg
  | OsEventMsg
  | DemoMsg
  | ClockPing;

export type ServerToAgent =
  | Welcome
  | AgentTrust
  | AgentChallenge
  | AgentLock
  | AgentUnlock
  | AgentMode
  | ClockPong
  | AgentError;

export type LiveEvent =
  | { type: "snapshot"; device_id: string | null; t: string; data: Snapshot }
  | { type: "trust"; device_id: string | null; t: string; data: TrustLive }
  | { type: "block_scored"; device_id: string | null; t: string; data: BlockScored }
  | { type: "context"; device_id: string | null; t: string; data: ContextLive }
  | { type: "enroll_progress"; device_id: string | null; t: string; data: EnrollProgress }
  | { type: "model"; device_id: string | null; t: string; data: ModelInfo }
  | { type: "anomaly"; device_id: string | null; t: string; data: AnomalyLive }
  | { type: "challenge"; device_id: string | null; t: string; data: ChallengeLive }
  | { type: "voice_stage"; device_id: string | null; t: string; data: VoiceStageLive }
  | { type: "voice_result"; device_id: string | null; t: string; data: VoiceResultLive }
  | { type: "decision"; device_id: string | null; t: string; data: DecisionLive }
  | { type: "marker"; device_id: string | null; t: string; data: MarkerPoint }
  | { type: "mode"; device_id: string | null; t: string; data: ModeLive }
  | { type: "lock"; device_id: string | null; t: string; data: LockLive }
  | { type: "unlock"; device_id: string | null; t: string; data: Record<string, never> }
  | { type: "label"; device_id: string | null; t: string; data: LabelLive }
  | { type: "presence"; device_id: string | null; t: string; data: PresenceLive }
  | { type: "health"; device_id: string | null; t: string; data: HealthLive }
  | { type: "feed"; device_id: string | null; t: string; data: FeedItem };

export const SCHEMA_VERSION = 1 as const;

export const FEATURE_SPEC = {
  "schema_version": 1,
  "modalities": {
    "keyboard": {
      "n_unit": "key_downs",
      "n_ref": 20,
      "enroll_gate": 100,
      "features": [
        {
          "name": "kb.hold_p50",
          "unit": "ms",
          "label": "key hold",
          "headline": true,
          "column": "kb_hold_p50"
        },
        {
          "name": "kb.hold_iqr",
          "unit": "ms",
          "label": "key hold spread",
          "headline": false,
          "column": "kb_hold_iqr"
        },
        {
          "name": "kb.hold_p50_L",
          "unit": "ms",
          "label": "left-hand key hold",
          "headline": false,
          "column": "kb_hold_p50_l"
        },
        {
          "name": "kb.hold_p50_R",
          "unit": "ms",
          "label": "right-hand key hold",
          "headline": false,
          "column": "kb_hold_p50_r"
        },
        {
          "name": "kb.hold_p50_space",
          "unit": "ms",
          "label": "space-bar hold",
          "headline": false,
          "column": "kb_hold_p50_space"
        },
        {
          "name": "kb.dd_p50",
          "unit": "ms",
          "label": "flight time",
          "headline": true,
          "column": "kb_dd_p50"
        },
        {
          "name": "kb.dd_iqr",
          "unit": "ms",
          "label": "flight time spread",
          "headline": false,
          "column": "kb_dd_iqr"
        },
        {
          "name": "kb.ud_p50",
          "unit": "ms",
          "label": "release-to-press gap",
          "headline": true,
          "column": "kb_ud_p50"
        },
        {
          "name": "kb.ud_iqr",
          "unit": "ms",
          "label": "release-to-press spread",
          "headline": false,
          "column": "kb_ud_iqr"
        },
        {
          "name": "kb.rollover_frac",
          "unit": "frac",
          "label": "key rollover",
          "headline": false,
          "column": "kb_rollover_frac"
        },
        {
          "name": "kb.dd_p50_same_hand",
          "unit": "ms",
          "label": "same-hand digraph",
          "headline": false,
          "column": "kb_dd_p50_same_hand"
        },
        {
          "name": "kb.dd_p50_cross_hand",
          "unit": "ms",
          "label": "cross-hand digraph",
          "headline": false,
          "column": "kb_dd_p50_cross_hand"
        },
        {
          "name": "kb.dd_p50_letter_space",
          "unit": "ms",
          "label": "letter-to-space",
          "headline": false,
          "column": "kb_dd_p50_letter_space"
        },
        {
          "name": "kb.dd_p50_space_letter",
          "unit": "ms",
          "label": "space-to-letter",
          "headline": false,
          "column": "kb_dd_p50_space_letter"
        },
        {
          "name": "kb.tri_p50",
          "unit": "ms",
          "label": "trigraph time",
          "headline": false,
          "column": "kb_tri_p50"
        },
        {
          "name": "kb.tri_iqr",
          "unit": "ms",
          "label": "trigraph spread",
          "headline": false,
          "column": "kb_tri_iqr"
        },
        {
          "name": "kb.speed_kps",
          "unit": "keys/s",
          "label": "typing speed",
          "headline": true,
          "column": "kb_speed_kps"
        },
        {
          "name": "kb.burst_len_mean",
          "unit": "keys",
          "label": "typing burst length",
          "headline": false,
          "column": "kb_burst_len_mean"
        },
        {
          "name": "kb.pause_rate",
          "unit": "per_key",
          "label": "pause rate",
          "headline": false,
          "column": "kb_pause_rate"
        },
        {
          "name": "kb.bksp_rate",
          "unit": "per_key",
          "label": "backspace rate",
          "headline": true,
          "column": "kb_bksp_rate"
        },
        {
          "name": "kb.bksp_run_mean",
          "unit": "keys",
          "label": "backspace run length",
          "headline": false,
          "column": "kb_bksp_run_mean"
        },
        {
          "name": "kb.pre_bksp_dd_p50",
          "unit": "ms",
          "label": "pause before correction",
          "headline": false,
          "column": "kb_pre_bksp_dd_p50"
        },
        {
          "name": "kb.post_bksp_dd_p50",
          "unit": "ms",
          "label": "pause after correction",
          "headline": false,
          "column": "kb_post_bksp_dd_p50"
        },
        {
          "name": "kb.shift_lead_p50",
          "unit": "ms",
          "label": "shift lead time",
          "headline": false,
          "column": "kb_shift_lead_p50"
        },
        {
          "name": "kb.chord_rate",
          "unit": "per_key",
          "label": "shortcut rate",
          "headline": false,
          "column": "kb_chord_rate"
        }
      ]
    },
    "mouse": {
      "n_unit": "actions",
      "n_ref": 5,
      "enroll_gate": 60,
      "features": [
        {
          "name": "ms.v_p50",
          "unit": "dd/s",
          "label": "pointer speed",
          "headline": true,
          "column": "ms_v_p50"
        },
        {
          "name": "ms.v_p90",
          "unit": "dd/s",
          "label": "peak pointer speed",
          "headline": false,
          "column": "ms_v_p90"
        },
        {
          "name": "ms.a_p50",
          "unit": "dd/s2",
          "label": "pointer acceleration",
          "headline": false,
          "column": "ms_a_p50"
        },
        {
          "name": "ms.jerk_p50",
          "unit": "dd/s3",
          "label": "pointer jerk",
          "headline": false,
          "column": "ms_jerk_p50"
        },
        {
          "name": "ms.curv_p50",
          "unit": "rad/dd",
          "label": "path curvature",
          "headline": true,
          "column": "ms_curv_p50"
        },
        {
          "name": "ms.angvel_p50",
          "unit": "rad/s",
          "label": "turning speed",
          "headline": false,
          "column": "ms_angvel_p50"
        },
        {
          "name": "ms.straightness_p50",
          "unit": "ratio",
          "label": "path straightness",
          "headline": true,
          "column": "ms_straightness_p50"
        },
        {
          "name": "ms.path_p50",
          "unit": "dd",
          "label": "stroke length",
          "headline": false,
          "column": "ms_path_p50"
        },
        {
          "name": "ms.dur_p50",
          "unit": "ms",
          "label": "stroke duration",
          "headline": false,
          "column": "ms_dur_p50"
        },
        {
          "name": "ms.t_peak_frac_p50",
          "unit": "frac",
          "label": "time to peak speed",
          "headline": false,
          "column": "ms_t_peak_frac_p50"
        },
        {
          "name": "ms.submoves_p50",
          "unit": "count",
          "label": "sub-movements",
          "headline": false,
          "column": "ms_submoves_p50"
        },
        {
          "name": "ms.click_hold_p50",
          "unit": "ms",
          "label": "click hold",
          "headline": true,
          "column": "ms_click_hold_p50"
        },
        {
          "name": "ms.pre_click_pause_p50",
          "unit": "ms",
          "label": "pause before click",
          "headline": false,
          "column": "ms_pre_click_pause_p50"
        },
        {
          "name": "ms.dblclick_p50",
          "unit": "ms",
          "label": "double-click interval",
          "headline": false,
          "column": "ms_dblclick_p50"
        },
        {
          "name": "ms.frac_pc",
          "unit": "frac",
          "label": "point-and-click share",
          "headline": false,
          "column": "ms_frac_pc"
        },
        {
          "name": "ms.frac_dd",
          "unit": "frac",
          "label": "drag share",
          "headline": false,
          "column": "ms_frac_dd"
        },
        {
          "name": "ms.dir_entropy",
          "unit": "bits",
          "label": "direction entropy",
          "headline": false,
          "column": "ms_dir_entropy"
        },
        {
          "name": "ms.dwell_rate",
          "unit": "per_s",
          "label": "hover rate",
          "headline": false,
          "column": "ms_dwell_rate"
        },
        {
          "name": "ms.dwell_p50",
          "unit": "ms",
          "label": "hover dwell",
          "headline": false,
          "column": "ms_dwell_p50"
        }
      ]
    },
    "scroll": {
      "n_unit": "bursts",
      "n_ref": 3,
      "enroll_gate": 30,
      "features": [
        {
          "name": "sc.burst_dur_p50",
          "unit": "ms",
          "label": "scroll burst duration",
          "headline": false,
          "column": "sc_burst_dur_p50"
        },
        {
          "name": "sc.burst_events_p50",
          "unit": "count",
          "label": "events per scroll burst",
          "headline": false,
          "column": "sc_burst_events_p50"
        },
        {
          "name": "sc.burst_dist_p50",
          "unit": "px",
          "label": "scroll burst distance",
          "headline": false,
          "column": "sc_burst_dist_p50"
        },
        {
          "name": "sc.v_peak_p50",
          "unit": "px/s",
          "label": "peak scroll speed",
          "headline": false,
          "column": "sc_v_peak_p50"
        },
        {
          "name": "sc.v_mean_p50",
          "unit": "px/s",
          "label": "scroll speed",
          "headline": true,
          "column": "sc_v_mean_p50"
        },
        {
          "name": "sc.iei_cv_p50",
          "unit": "ratio",
          "label": "scroll rhythm variability",
          "headline": false,
          "column": "sc_iei_cv_p50"
        },
        {
          "name": "sc.inter_burst_p50",
          "unit": "ms",
          "label": "gap between scrolls",
          "headline": false,
          "column": "sc_inter_burst_p50"
        },
        {
          "name": "sc.reversal_rate",
          "unit": "per_burst",
          "label": "scroll reversals",
          "headline": false,
          "column": "sc_reversal_rate"
        },
        {
          "name": "sc.momentum_frac",
          "unit": "frac",
          "label": "momentum share",
          "headline": false,
          "column": "sc_momentum_frac"
        },
        {
          "name": "sc.horizontal_frac",
          "unit": "frac",
          "label": "horizontal scroll share",
          "headline": false,
          "column": "sc_horizontal_frac"
        }
      ]
    },
    "workflow": {
      "n_unit": "transitions",
      "n_ref": 3,
      "enroll_gate": 20,
      "features": [
        {
          "name": "wf.switch_rate",
          "unit": "per_min",
          "label": "app switching rate",
          "headline": true,
          "column": "wf_switch_rate"
        },
        {
          "name": "wf.switch_latency_p50",
          "unit": "ms",
          "label": "task-switch latency",
          "headline": false,
          "column": "wf_switch_latency_p50"
        },
        {
          "name": "wf.kbd_switch_frac",
          "unit": "frac",
          "label": "keyboard app-switch share",
          "headline": false,
          "column": "wf_kbd_switch_frac"
        },
        {
          "name": "wf.win_change_rate",
          "unit": "per_min",
          "label": "window change rate",
          "headline": false,
          "column": "wf_win_change_rate"
        },
        {
          "name": "wf.tab_chord_rate",
          "unit": "per_min",
          "label": "tab shortcut rate",
          "headline": false,
          "column": "wf_tab_chord_rate"
        },
        {
          "name": "wf.k2m_p50",
          "unit": "ms",
          "label": "keyboard-to-mouse time",
          "headline": false,
          "column": "wf_k2m_p50"
        },
        {
          "name": "wf.m2k_p50",
          "unit": "ms",
          "label": "mouse-to-keyboard time",
          "headline": false,
          "column": "wf_m2k_p50"
        },
        {
          "name": "wf.app_dwell_p50",
          "unit": "ms",
          "label": "time per app",
          "headline": false,
          "column": "wf_app_dwell_p50"
        },
        {
          "name": "wf.markov_ll",
          "unit": "nats",
          "label": "app transition pattern",
          "headline": false,
          "column": "wf_markov_ll"
        }
      ]
    },
    "temporal": {
      "n_unit": "events",
      "n_ref": 100,
      "enroll_gate": 60,
      "features": [
        {
          "name": "tp.rate",
          "unit": "ev/s",
          "label": "event rate",
          "headline": true,
          "column": "tp_rate"
        },
        {
          "name": "tp.B",
          "unit": "score",
          "label": "burstiness",
          "headline": true,
          "column": "tp_b"
        },
        {
          "name": "tp.Bn",
          "unit": "score",
          "label": "burstiness (finite-n)",
          "headline": false,
          "column": "tp_bn"
        },
        {
          "name": "tp.M",
          "unit": "score",
          "label": "inter-event memory",
          "headline": false,
          "column": "tp_m"
        },
        {
          "name": "tp.idle_frac",
          "unit": "frac",
          "label": "idle share",
          "headline": true,
          "column": "tp_idle_frac"
        },
        {
          "name": "tp.idle_p50",
          "unit": "ms",
          "label": "idle gap",
          "headline": false,
          "column": "tp_idle_p50"
        },
        {
          "name": "tp.idle_p90",
          "unit": "ms",
          "label": "long idle gap",
          "headline": false,
          "column": "tp_idle_p90"
        },
        {
          "name": "tp.bp_0_05",
          "unit": "frac",
          "label": "rhythm power 0-0.5 Hz",
          "headline": false,
          "column": "tp_bp_0_05"
        },
        {
          "name": "tp.bp_05_2",
          "unit": "frac",
          "label": "rhythm power 0.5-2 Hz",
          "headline": false,
          "column": "tp_bp_05_2"
        },
        {
          "name": "tp.bp_2_5",
          "unit": "frac",
          "label": "rhythm power 2-5 Hz",
          "headline": false,
          "column": "tp_bp_2_5"
        },
        {
          "name": "tp.bp_5_10",
          "unit": "frac",
          "label": "rhythm power 5-10 Hz",
          "headline": false,
          "column": "tp_bp_5_10"
        },
        {
          "name": "tp.bp_10_25",
          "unit": "frac",
          "label": "rhythm power 10-25 Hz",
          "headline": false,
          "column": "tp_bp_10_25"
        },
        {
          "name": "tp.spec_entropy",
          "unit": "bits",
          "label": "rhythm spectral entropy",
          "headline": false,
          "column": "tp_spec_entropy"
        },
        {
          "name": "tp.peak_hz",
          "unit": "Hz",
          "label": "dominant rhythm",
          "headline": true,
          "column": "tp_peak_hz"
        },
        {
          "name": "tp.centroid_hz",
          "unit": "Hz",
          "label": "rhythm centroid",
          "headline": false,
          "column": "tp_centroid_hz"
        },
        {
          "name": "tp.acf_peak_lag",
          "unit": "ms",
          "label": "periodicity lag",
          "headline": false,
          "column": "tp_acf_peak_lag"
        },
        {
          "name": "tp.acf_peak",
          "unit": "corr",
          "label": "periodicity strength",
          "headline": false,
          "column": "tp_acf_peak"
        }
      ]
    }
  },
  "signature": {
    "keyboard": {
      "hold duration": [
        "kb.hold_p50",
        "kb.hold_iqr",
        "kb.hold_p50_L",
        "kb.hold_p50_R",
        "kb.hold_p50_space"
      ],
      "inter-key latency": [
        "kb.dd_p50",
        "kb.dd_iqr",
        "kb.dd_p50_same_hand",
        "kb.dd_p50_cross_hand",
        "kb.dd_p50_letter_space",
        "kb.dd_p50_space_letter",
        "kb.ud_p50",
        "kb.ud_iqr"
      ],
      "digraph/trigraph timing": [
        "kb.dd_p50_same_hand",
        "kb.dd_p50_cross_hand",
        "kb.dd_p50_letter_space",
        "kb.dd_p50_space_letter",
        "kb.tri_p50",
        "kb.tri_iqr"
      ],
      "typing cadence": [
        "kb.speed_kps"
      ],
      "pause/burst behavior": [
        "kb.burst_len_mean",
        "kb.pause_rate"
      ],
      "correction behavior": [
        "kb.bksp_rate",
        "kb.bksp_run_mean",
        "kb.pre_bksp_dd_p50",
        "kb.post_bksp_dd_p50"
      ]
    },
    "mouse": {
      "velocity": [
        "ms.v_p50",
        "ms.v_p90"
      ],
      "acceleration": [
        "ms.a_p50"
      ],
      "curvature": [
        "ms.curv_p50",
        "ms.angvel_p50"
      ],
      "jerk/smoothness": [
        "ms.jerk_p50",
        "ms.submoves_p50"
      ],
      "click timing": [
        "ms.click_hold_p50",
        "ms.pre_click_pause_p50",
        "ms.dblclick_p50"
      ],
      "hover/dwell behavior": [
        "ms.dwell_rate",
        "ms.dwell_p50"
      ]
    },
    "scroll": {
      "velocity": [
        "sc.v_peak_p50",
        "sc.v_mean_p50"
      ],
      "burst length": [
        "sc.burst_dur_p50",
        "sc.burst_events_p50",
        "sc.burst_dist_p50"
      ],
      "inter-scroll timing": [
        "sc.inter_burst_p50",
        "sc.iei_cv_p50"
      ],
      "direction/reversals": [
        "sc.reversal_rate"
      ]
    },
    "workflow": {
      "application switching": [
        "wf.switch_rate"
      ],
      "task-switch latency": [
        "wf.switch_latency_p50"
      ],
      "app transition patterns": [
        "wf.markov_ll"
      ],
      "window/tab behavior": [
        "wf.win_change_rate",
        "wf.tab_chord_rate"
      ],
      "keyboard-mouse transitions": [
        "wf.k2m_p50",
        "wf.m2k_p50"
      ]
    },
    "temporal": {
      "event frequency": [
        "tp.rate"
      ],
      "burstiness": [
        "tp.B",
        "tp.Bn",
        "tp.M"
      ],
      "idle intervals": [
        "tp.idle_frac",
        "tp.idle_p50",
        "tp.idle_p90"
      ],
      "periodicity": [
        "tp.acf_peak_lag",
        "tp.acf_peak"
      ],
      "frequency-domain / FFT": [
        "tp.bp_0_05",
        "tp.bp_05_2",
        "tp.bp_2_5",
        "tp.bp_5_10",
        "tp.bp_10_25",
        "tp.spec_entropy",
        "tp.peak_hz",
        "tp.centroid_hz"
      ]
    }
  },
  "enums": {
    "app_categories": [
      "browser",
      "ide",
      "terminal",
      "chat",
      "docs",
      "media",
      "system",
      "other"
    ],
    "key_classes": [
      "L_LETTER",
      "R_LETTER",
      "DIGIT",
      "PUNCT",
      "SPACE",
      "ENTER",
      "BKSP",
      "TAB",
      "ESC",
      "ARROW",
      "NAV",
      "FKEY",
      "SHIFT",
      "CMD",
      "CTRL",
      "OPT",
      "CAPS",
      "OTHER"
    ],
    "modifier_classes": [
      "SHIFT",
      "CMD",
      "CTRL",
      "OPT",
      "CAPS"
    ],
    "chord_kinds": [
      "tab_new",
      "tab_close",
      "tab_jump",
      "tab_cycle",
      "app_switch_kbd",
      "window_cycle",
      "other_cmd"
    ],
    "app_switch_via": [
      "cmdtab",
      "click",
      "other"
    ]
  }
} as const;

export const TRUST_CONFIG = {
  "cap": 0.995,
  "levels": {
    "normal": 0.8,
    "watch": 0.4
  },
  "anchors": {
    "verify": 0.97,
    "reset": 0.97,
    "model_activate": 0.97,
    "screen_unlock": 0.8,
    "remote": 0.3,
    "restart_stale": 0.3,
    "new_device_enroll": 0.97,
    "new_device_monitor": 0.3,
    "rearm_default": 0.31
  },
  "arming": {
    "threshold": 0.4,
    "consecutive_ticks": 2,
    "rearm_above": 0.6,
    "cooldown_s": 60,
    "proactive_expiry_s": 180
  },
  "weights": {
    "keyboard": 1.0,
    "mouse": 1.0,
    "scroll": 0.5,
    "workflow": 0.4,
    "temporal": 0.05
  },
  "policy": {
    "tiers": {
      "R0": {
        "min_conf": 0.4,
        "actions": [
          "view"
        ]
      },
      "R1": {
        "min_conf": 0.6,
        "purchase_below_cents": 10000
      },
      "R2": {
        "min_conf": 0.8,
        "purchase_below_cents": 50000,
        "actions": [
          "export"
        ]
      },
      "R3": {
        "min_conf": 0.9,
        "actions": [
          "add_payee",
          "password_change"
        ]
      }
    },
    "trans_status": {
      "allow": "Y",
      "step_up": "C",
      "block": "N"
    },
    "checkout_badge_min": 0.95
  },
  "binding": {
    "heartbeat_max_s": 30,
    "window_s": 20,
    "lags_s": [
      -1,
      0,
      1
    ],
    "min_pearson": 0.5,
    "min_active_s": 5,
    "count_ratio": 0.8,
    "count_ratio_frac": 0.8
  }
} as const;

export const HEADLINE_COLUMNS: readonly string[] = ["kb_hold_p50", "kb_dd_p50", "kb_ud_p50", "kb_speed_kps", "kb_bksp_rate", "ms_v_p50", "ms_curv_p50", "ms_straightness_p50", "ms_click_hold_p50", "sc_v_mean_p50", "wf_switch_rate", "tp_rate", "tp_b", "tp_idle_frac", "tp_peak_hz"];

const _FEATURES: Record<string, { label: string; unit: string; modality: Modality }> = {};
for (const [m, ms] of Object.entries(FEATURE_SPEC.modalities)) {
  for (const f of ms.features) _FEATURES[f.name] = { label: f.label, unit: f.unit, modality: m as Modality };
}
export function featureInfo(name: string) {
  return _FEATURES[name] ?? { label: name, unit: "", modality: "keyboard" as Modality };
}
